001-counter-app/index.html, 001-counter-app/script.js
This is a simple counter app. Here clicking on the `+` button will increase the count and `-` will do the opposite.
=> [001] Add increase count function

002-number-comparator/bondodev/index.html
=> [002] Add number comparator assignment

002-number-comparator/Talha/index.html, 002-number-comparator/Talha/number-comparator.js
This is a simple number comparison application. Here, Users can compare numbers by clicking compare button and also can reset it by pressing reset button.
=> [002]Added number comparator function with reset functionality

002-number-comparator/bondodev/index.html, 002-number-comparator/bondodev/number-comparator.js
=> [002] Add Number Comparator App

002-number-comparator/nazma98/index.html, 002-number-comparator/nazma98/number-comparator.js
Here is a simple number comparator app. This app takes two numbers as inputs and finds out which one is greater or whether they are equal.
=> [002] Add number comparator functions with reset

.github/workflows/static.yml
=> [000] Add github actions to deploy pages

001-counter-app/Tamjid/index.html, 001-counter-app/Tamjid/script.js, 002-number-comparator/Tamjid/index.html, 002-number-comparator/Tamjid/script.js, 003-grade-calculator/Tamjid/index.html, 003-grade-calculator/Tamjid/script.js
**Added a javascript file**
**Added reset button**
**Added different colours for different grade**
For lower grades: red
For average grades: blue
For best grades: green
=> Added a javascript file and reset button

001-counter-app/sumiya-yasmin/index.html, 001-counter-app/sumiya-yasmin/script.js
=> [001] Add Reset Button and Add Decrement and Reset Function.

003-grade-calculator/nazma98/grade-calculator.js, 003-grade-calculator/nazma98/index.html, index.html
Grade Calculator
This is a simple grade calculator. It can calculate the grades of scores given in the range of `0` - `100`.
The grading system states - 
- 80% or above - `A+`
- 75% to <80% - `A`
- 70% to <75% - `A-`
- 65% to <70% - `B+`
- 60% to <65% - `B`
- 55% to <60% - `B-`
- 50% to <55% - `C+`
- 45% to <50% - `C`
- 40% to <45% - `D`
- Less than 40% - `F`
=> [003] Add grade calculator app

003-grade-calculator/Talha/grade-calculator.js, 003-grade-calculator/Talha/index.html, index.html
This is a simple grade calculator app. Here, User can calculate grade according to their given input. Based on the given input user's grade will be shown.
=> [003] Grade Calculator App

003-grade-calculator/anikatasnim/grade-calculator.js, 003-grade-calculator/anikatasnim/index.html
A Grade Calculator that provides the proper grade after providing the valid score.
=> [003] Grade calculator app with reset button

001-counter-app/Sakib 2.2/index.html, 001-counter-app/Sakib 2.2/script.js
[001]-Counter App
Added increasing and decreasing button
also added an option for overflowing and not take negative values
=> [001]-counter-app

002-number-comparator/sumiya-yasmin/index.html, 002-number-comparator/sumiya-yasmin/number-comparator.js, index.html
This is a number comparator app that compares any two given numbers and shows which number is greater or equal.
> When two different numbers are input, it will always show which number is greater. 
For two same numbers, it also tests if the numbers are equal.
=> [002] Add number comparator app 

003-grade-calculator/promi/grade-calculator.js, 003-grade-calculator/promi/index.html
Grade Calculator
This grade calculator app determines the grade based on the input marks.
=>  add grade-calculator 

001-counter-app/Alamin/index.html, 001-counter-app/Alamin/script.js
=> [001] Add increment and decrement function

index.html
Added:
001-counter app on the list
002-number comparator app on the list
003-grade calculator app on the list
=> Tamjid/Added projects on List

004-number-table/Talha/index.html, 004-number-table/Talha/multiplication-table.js
This is a simple javascript app to generate number table according to user input number.
Generate table inserting input
Validation check
Reset button to reset
=> [004] Number Table App by Talha

003-grade-calculator/shobuz/grade_calculator.js, 003-grade-calculator/shobuz/index.html
=> [003]added my grade calculator project

001-counter-app/promi/index.html, 001-counter-app/promi/script.js
=> add counter-app

001-counter-app/Talha/script.js
This is a simple counter app where we can increase or decrease count by clicking '+' and '-' button.
Increasing Count
Decreasing Count
Count Overflow
Count Negative warning
=> [001] Added counter app increment and decrement function

001-counter-app/Dipu/index.html, 001-counter-app/Dipu/script.js
- [1 ]  (+)button increment number
- [2] (-) button decrement number
- [3] reset button again reset number zero
=> Added increment and decrement function

005-number-table-1-10/bongodev/index.html, 005-number-table-1-10/bongodev/multiplication-table.js
=> [005] Render number tables for 1-10 using nested loops

script.js
=> [000] Add contributor in script js file

003-grade-calculator/Alamin/grade-calculator.js, 003-grade-calculator/Alamin/index.html
The Grade Calculator app allows users to input a score between 0 and 100 to determine their grade. It validates the input, displays the corresponding grade with dynamic styling, and provides error messages for invalid entries. Users can reset the input and results with a clear button.
=> [003] Added grade calculator function

004-number-table/promi/index.html, 004-number-table/promi/multiplication-table.js
This is a multiplication table
It generate s multiplication table based on the input number
=> add multiplication-table

005-number-table-1-10/thanwin/index.html, 005-number-table-1-10/thanwin/multiplication-table.js
It allows user to generate multiplication table 1 to 10. 
Here is the screenshot of this project.
=> [005] Add multiplication table-1-10 project

005-number-table-1-10/Alamin/index.html, 005-number-table-1-10/Alamin/multiplication-table.js
This project generate multiplication tables for numbers 1 to 10 using the "Generate Table" button, which dynamically displays the tables in two rows. The "Reset" button allows users to clear the tables for a fresh start. With its interactive functionality and sleek layout, the page is ideal for educational purposes or learning multiplication concepts.
=> [005] Number table-1-10

005-number-table-1-10/Dipu/index.html, 005-number-table-1-10/Dipu/multiplication-table.js
- [ 1] Generate button create multiplication table.
=> Added Multiplication Table

005-number-table-1-10/nazma98/index.html, 005-number-table-1-10/nazma98/multiplication-table.js
This multiplication table app generates multiplication tables from number 0 to 10.
**Interface**
**The multiplication tables**
=> [005] Add multiplication table 1-10 app

004-number-table/anikatasnim/index.html, 004-number-table/anikatasnim/multiplication-table.js
Number Table
A number table generator app that generates the multiplication table for a given positive integer.  
The app includes a reset button, proper error checking, and visual elements to enhance comprehension.
1. **Verify Basic Functionality**:  
2. **Error Handling**:  
3. **Reset Functionality**:  
4. **Visual Elements**:  
5. **Performance**:
=> [004] Number Table

005-number-table-1-10/Talha/index.html, 005-number-table-1-10/Talha/multiplication-table.js
This is a simple javascript app showing multiplication table from 1 to 10.
After clicking generate button 
After clicking reset button
After clicking generate button multiple times
=> [005] Multiplication Table from 1 to 10

004-number-table/bongodev/multiplication-table.js, script.js
Use forEach
Use arrow functions
Use list de-structuring
=> [004] Code optimization

001-counter-app/sumiya-yasmin/script.js, 004-number-table/sumiya-yasmin/index.html, 004-number-table/sumiya-yasmin/multiplication-table.js, 005-number-table-1-10/sumiya-yasmin/index.html, 005-number-table-1-10/sumiya-yasmin/multiplication-table.js
This is a number table that will display multiplication table from number 1 to number 10
=> [005] Add number-table-1-10

script.js
=> [000] Added my details in contributor list

005-number-table-1-10/Alamin/index.html, 005-number-table-1-10/Alamin/multiplication-table.js, script.js
=> [000] Landing-page

script.js
=> [000] Added my information in the contributor's list on landing page

006-employee-table/bongodev/index.html, 006-employee-table/bongodev/script.js
=> [006] Add employee table project

script.js
=> Add my name(thanwin) to contributor list

005-number-table-1-10/Tamjid/index.html, 005-number-table-1-10/Tamjid/script.js
Added a reset button:
Solved a problem where the generate button continuously generated unnecessary tables:
Added colours to the table:
=> Tamjid/Added 005-number table-1-10

004-number-table/Toukir/index.html, 004-number-table/Toukir/multiplication-table.js
=> [004] add number calculator

002-number-comparator/promi/index.html, 002-number-comparator/promi/number-comparator.js
=> resolve issues of number-comparator

001-counter-app/Alme/index.html, 001-counter-app/Alme/script.js
The counter app UI is as follows:
=> [001]-Counter App- increase button, decrease button, reset button

007-e-commerce/bongodev/app.js, 007-e-commerce/bongodev/index.html, script.js
=> [007] Simple E-commerce

006-employee-table/sumiya-yasmin/index.html, 006-employee-table/sumiya-yasmin/script.js
=> [006] Added employee data  table

006-employee-table/nazma98/index.html, 006-employee-table/nazma98/script.js
This app displays a table containing employee id,  names, positions and their respective departments
=> [006]  Add employee table 

005-number-table-1-10/Toukir/index.html, 005-number-table-1-10/Toukir/multiplication-table.js
005-number-table-1-10
An interactive web-based tool that generates multiplication tables from 1 to 10, dynamically displaying them in two sections using JavaScript. It features a reset option to clear the tables and applies alternate styling for better visualization
=> Rander number tables for 1-10 using nested loops

004-number-table/Talha/index.html, 004-number-table/Talha/multiplication-table.js
This is a simple number table where it allows user to get number table according to their input.
After giving input generated table
After giving negative integer
After giving no input
=> [004] Number table code reduction using arrow function, forEach and destructuring

script.js
=> Added Contributor list

007-e-commerce/thanwin/index.html, 007-e-commerce/thanwin/index.js
This is a simple ecommerce project using Vanilla JavaScript. Users can filter products based on category and users can also add items to the cart. Cart also has increase quantity, decrease quantity and remove items functionality.  The cart items are stored in localStorage, ensuring the cart data persists across page reloads.
Here's some screenshot of this project.
=> [007] Add Ecommerce project

006-employee-table/Dipu/index.html, 006-employee-table/Dipu/script.js
=> Added employee table

002-number-comparator/Alme/index.html, 002-number-comparator/Alme/number-comparator.js, 003-grade-calculator/Alme/grade-calculator.js, 003-grade-calculator/Alme/index.html
=> [003] Grade Calculator

006-employee-table/anikatasnim/index.html, 006-employee-table/anikatasnim/script.js
=> [006] Employee Table

008-render-products/bongodev/index.html, 008-render-products/bongodev/js/script.js, script.js
=> [008] Render products (Promise, async-await)

007-e-commerce/Talha/index.html, 007-e-commerce/Talha/js/app.js
=> [007] Fixed apply filter problem

006-employee-table/taherabu/index.html, 006-employee-table/taherabu/script.js
=> [006] Add employee Management project(Abu Taher)

004-number-table/Alme/index.html, 004-number-table/Alme/multiplication-table.js
It's a html and JavaScript based mini project where I've tried to implement the logic of displaying a table of integer number. 
The projects UI looks like as follows:
=> [004] number table/ Busrana Alme

008-render-products/thanwin/index.html, 008-render-products/thanwin/index.js
=> [008] Render products

004-number-table/Alme/index.html, 004-number-table/Alme/multiplication-table.js, 005-number-table-1-10/Alme/index.html, 005-number-table-1-10/Alme/multiplication-table.js
First view: 
The tables look like as follows:
=> Number table 1 to 10

004-number-table/nazma98/index.html, 004-number-table/nazma98/multiplication-table.js
This is a simple multiplication table generator app. The user has to input an integer and a multiplication table of the given number will be generated automatically.
**The App interface**
**After a valid input is provided**
**After a invalid input is provided**
**After the input field is kept blank**
=> [004] Add number table app

008-render-products/Dipu/index.html, 008-render-products/Dipu/script.js
=> Added renderproducts

004-number-table/Alme/index.html, 004-number-table/Alme/multiplication-table.js, 005-number-table-1-10/Alme/index.html, 005-number-table-1-10/Alme/multiplication-table.js, 006-employee-table/Alme/index.html, 006-employee-table/Alme/script.js
=> [006] Employee Table/ Busrana Alme

001-counter-app/Shifat/index.html, 001-counter-app/Shifat/script.js
I have added the JavaScript code for the counter app.
=> completed counter app

script.js
I have added my name to the contributor list.
=> [shifat97] Add name to contributor list

001-counter-app/Mohyminul-Islam/app.js, 001-counter-app/Mohyminul-Islam/index.html
=> [Mohyminul-Islam] 001-Counter-App

.vscode/settings.json, 001-counter-app/Asha/index.html, 001-counter-app/Asha/script.js
=> [001][Asha] Completed Counter App

001-counter-app/Tanziful/index.html, 001-counter-app/Tanziful/script.js, 002-number-comparator/Tanziful/index.html, 002-number-comparator/Tanziful/script.js
The Number Comparator App is a simple interactive web tool built using HTML, Tailwind CSS, and JavaScript. It allows users to input two numbers and compare them. The app then displays whether the first number is greater than, less than, or equal to the second number. It includes basic input validation and a reset feature. This project helps beginners practice DOM manipulation, event handling, and form validation.
=> [002] [Tanziful] Number comparator app

003-grade-calculator/Shifat/index.html, 003-grade-calculator/Shifat/script.js
I have added the grade calculator app.
=> [003][shifat97] Completed grade calculator app

002-number-comparator/Shifat/index.html, 002-number-comparator/Shifat/script.js
I have added the number comparator project.
=> [002][shifat97] Completed number comparator project

002-number-comparator/Asha/index.html, 002-number-comparator/Asha/script.js
=> [002][asha]complete Number Comparator

001-counter-app/armaanepiic/script.js
=> counter app created and applied css

script.js
[armaanepiic] updated script.js file.
=> added my info from armaanepiic

006-employee-table/Shifat/index.html, 006-employee-table/Shifat/script.js
Added employee data using the .map() function.
=> [006][shifat97] Add employee table

002-number-comparator/muna47/index.html, 002-number-comparator/muna47/script.js
check two numbers and compare if they are equal or large or small. For input handling if no numbers are entered it shows to enter before comparing again.
=> [002][mymuna] number comparator

003-grade-calculator/armaanepiic/index.html, 003-grade-calculator/armaanepiic/script.js
Go live from the index.html file. Enter a score and you can see the grade.
=> [003] [armaanepiic] grade calculator created with JS DOM.

004-number-table/armaanepiic/index.html, 004-number-table/armaanepiic/multiplication-table.js
This project shows a number table taking a number as input.
=> [004] [armaanepiic] number table project complete

006-employee-table/armaanepiic/index.html, 006-employee-table/armaanepiic/script.js
It shows an employee table taking data from JSON object.
=> [006] [armaanepiic] employee-table

002-number-comparator/armaanepiic/index.html, 002-number-comparator/armaanepiic/script.js
This project take two number as input and compare between them.
=> [002][armaanepiic] Number Comparator project

006-employee-table/Sakib/index.html, 006-employee-table/Sakib/script.js
Here I try to show all the employee of a company in a list, i tried for adding edit and delete and add employee option but dont understand that properly 
- run the code
- we can see the list of employee
-
=> [006][sakib]completed employee table

001-counter-app/Eva/Index.html, 001-counter-app/Eva/script.js, 002-number-comparator/Eva/index.html, 002-number-comparator/Eva/test.js, 003-grade-calculator/EVA/index.html, 003-grade-calculator/EVA/script.js, 004-number-table/EVA/Multiplication-table.js, 004-number-table/EVA/index.html, 005-number-table-1-10/EVA/index.html, 005-number-table-1-10/EVA/multiplication-table.js
=> [EVA]_005_number_table_1-10

004-number-table/Tasin/index.html, 004-number-table/Tasin/multiplication-table.js
1.First of all we create a file index.html and copy the code from bongodev folder.
2.create a mulplication-table.js file 
3.The code grabs the input box, the generate button, and the body of the table from the HTML page using their IDs.
4.Add Click Event Listener to the Button and define the generateTable function. Here, we use for loop and define the row .
5. Clear previous table before adding new rows. Then, generate rows dynamically.
6. Create a table row which starts a new row for the table.
7. Now create an array of the data for the row. This row will display something like:5*3=15 , where 5 is the number and 3 rowNo and result is 15.
8. Loop through rowData and create table cells. Create a cell and puts the text inside then save it to a list called cells. Append all cells in the …
=> [Tasin]004 number table
